apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
spec:
  selector:
    matchLabels:
      name: project
  replicas: 3
  template:
    metadata:
      labels:
        name: project
    spec:
      containers:
      - name: projectcontainer
        image: moamensoltan/project:projectimage
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
